language: python
python:
  - "3.5"
  - "3.6"
  - "nightly"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script: nosetests --with-coverage --cover-package=src
after_success:
  coveralls